export default class RoomPositionExtension extends RoomPosition {
    public onPath(path: number[], idx: number): boolean {
        let now = (this.x & 0b111) | (this.y & 0b111 << 3);
        let [r1, r2] = [Math.ceil(idx / 3), idx % 3 * 10 + 4];
        return now === (path[r1] >> r2 & 0b111111);
    }

    /**
     * generated by copilot
     * */
    public dirToPos(dir: DirectionConstant): RoomPosition {
        let x = this.x + (dir & 1) - (dir & 2);
        let y = this.y + ((dir & 2) >> 1) - (dir & 4);
        return new RoomPosition(x, y, this.roomName);
    }
}